// This file is part of the QuickSig library.
// Copyright 2008 Stefan Dragnev.
// The library and all its files are distributed under the MIT license.
// See the full text of the license in the accompanying LICENSE.txt file or at http://www.opensource.org/licenses/mit-license.php

#include "stdafx.h"

#include "../include/QuickSig.h"
#include "../include/SetStorage.h"
#include "../include/FixedArrayStorage.h"
#include "../include/Synchronization.h"
#include "../include/ResultCombiners.h"

using namespace QuickSig;

void PolicyCompilationTest()
{
	Signal1<int, detail::DefaultPoliciesArg> Sig;
	Signal1<int, NoSync> Siga;
	Signal1<int, InstanceLock> Sigb;
	Signal1<int, ProcesswideLock> Sigc;
	Signal1<int, ArrayStorage> Sigd;
	Signal1<int, SortedArrayStorage> Sige;
	Signal1<int, SetStorage> Sigf;
	Signal1<int, NoResult> Sigg;
	Signal1<int, All<true>> Sigh;
	Signal1<int, Any<true>> Sigi;

	Signal1<int, Policies<>> Sig0;
	Signal1<int, Policies<NoSync>> Sig1;
	Signal1<int, Policies<InstanceLock>> Sig2;
	Signal1<int, Policies<ProcesswideLock>> Sig3;
	Signal1<int, Policies<ArrayStorage>> Sig4;
	Signal1<int, Policies<SortedArrayStorage>> Sig5;
	Signal1<int, Policies<SetStorage>> Sig6;
	Signal1<int, Policies<FixedArrayStorage<20>>> Sig7;
	Signal1<int, Policies<NoResult>> Sig8;
	Signal1<int, Policies<All<true>>> Sig9;
	Signal1<int, Policies<Any<true>>> Sig10;
	Signal1<int, Policies<detail::DefaultPoliciesArg>> Sig11;
	Signal1<int, Policies<NoSync>> Sig12;
	Signal1<int, Policies<NoSync, ArrayStorage>> Sig13;
	Signal1<int, Policies<NoSync, SortedArrayStorage>> Sig14;
	Signal1<int, Policies<NoSync, SetStorage>> Sig15;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>>> Sig16;
	Signal1<int, Policies<NoSync, NoResult>> Sig17;
	Signal1<int, Policies<NoSync, All<true>>> Sig18;
	Signal1<int, Policies<NoSync, Any<true>>> Sig19;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg>> Sig20;
	Signal1<int, Policies<InstanceLock>> Sig21;
	Signal1<int, Policies<InstanceLock, ArrayStorage>> Sig22;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage>> Sig23;
	Signal1<int, Policies<InstanceLock, SetStorage>> Sig24;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>>> Sig25;
	Signal1<int, Policies<InstanceLock, NoResult>> Sig26;
	Signal1<int, Policies<InstanceLock, All<true>>> Sig27;
	Signal1<int, Policies<InstanceLock, Any<true>>> Sig28;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg>> Sig29;
	Signal1<int, Policies<ProcesswideLock>> Sig30;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage>> Sig31;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage>> Sig32;
	Signal1<int, Policies<ProcesswideLock, SetStorage>> Sig33;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>>> Sig34;
	Signal1<int, Policies<ProcesswideLock, NoResult>> Sig35;
	Signal1<int, Policies<ProcesswideLock, All<true>>> Sig36;
	Signal1<int, Policies<ProcesswideLock, Any<true>>> Sig37;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg>> Sig38;
	Signal1<int, Policies<ArrayStorage>> Sig39;
	Signal1<int, Policies<ArrayStorage, NoSync>> Sig40;
	Signal1<int, Policies<ArrayStorage, InstanceLock>> Sig41;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock>> Sig42;
	Signal1<int, Policies<ArrayStorage, NoResult>> Sig43;
	Signal1<int, Policies<ArrayStorage, All<true>>> Sig44;
	Signal1<int, Policies<ArrayStorage, Any<true>>> Sig45;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg>> Sig46;
	Signal1<int, Policies<SortedArrayStorage>> Sig47;
	Signal1<int, Policies<SortedArrayStorage, NoSync>> Sig48;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock>> Sig49;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock>> Sig50;
	Signal1<int, Policies<SortedArrayStorage, NoResult>> Sig51;
	Signal1<int, Policies<SortedArrayStorage, All<true>>> Sig52;
	Signal1<int, Policies<SortedArrayStorage, Any<true>>> Sig53;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg>> Sig54;
	Signal1<int, Policies<SetStorage>> Sig55;
	Signal1<int, Policies<SetStorage, NoSync>> Sig56;
	Signal1<int, Policies<SetStorage, InstanceLock>> Sig57;
	Signal1<int, Policies<SetStorage, ProcesswideLock>> Sig58;
	Signal1<int, Policies<SetStorage, NoResult>> Sig59;
	Signal1<int, Policies<SetStorage, All<true>>> Sig60;
	Signal1<int, Policies<SetStorage, Any<true>>> Sig61;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg>> Sig62;
	Signal1<int, Policies<FixedArrayStorage<20>>> Sig63;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync>> Sig64;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock>> Sig65;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock>> Sig66;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult>> Sig67;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>>> Sig68;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>>> Sig69;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig70;
	Signal1<int, Policies<NoResult>> Sig71;
	Signal1<int, Policies<NoResult, NoSync>> Sig72;
	Signal1<int, Policies<NoResult, InstanceLock>> Sig73;
	Signal1<int, Policies<NoResult, ProcesswideLock>> Sig74;
	Signal1<int, Policies<NoResult, ArrayStorage>> Sig75;
	Signal1<int, Policies<NoResult, SortedArrayStorage>> Sig76;
	Signal1<int, Policies<NoResult, SetStorage>> Sig77;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>>> Sig78;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg>> Sig79;
	Signal1<int, Policies<All<true>>> Sig80;
	Signal1<int, Policies<All<true>, NoSync>> Sig81;
	Signal1<int, Policies<All<true>, InstanceLock>> Sig82;
	Signal1<int, Policies<All<true>, ProcesswideLock>> Sig83;
	Signal1<int, Policies<All<true>, ArrayStorage>> Sig84;
	Signal1<int, Policies<All<true>, SortedArrayStorage>> Sig85;
	Signal1<int, Policies<All<true>, SetStorage>> Sig86;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>>> Sig87;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg>> Sig88;
	Signal1<int, Policies<Any<true>>> Sig89;
	Signal1<int, Policies<Any<true>, NoSync>> Sig90;
	Signal1<int, Policies<Any<true>, InstanceLock>> Sig91;
	Signal1<int, Policies<Any<true>, ProcesswideLock>> Sig92;
	Signal1<int, Policies<Any<true>, ArrayStorage>> Sig93;
	Signal1<int, Policies<Any<true>, SortedArrayStorage>> Sig94;
	Signal1<int, Policies<Any<true>, SetStorage>> Sig95;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>>> Sig96;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg>> Sig97;
	Signal1<int, Policies<detail::DefaultPoliciesArg>> Sig98;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync>> Sig99;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock>> Sig100;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock>> Sig101;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage>> Sig102;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage>> Sig103;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage>> Sig104;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig105;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult>> Sig106;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>>> Sig107;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>>> Sig108;
	Signal1<int, Policies<NoSync>> Sig109;
	Signal1<int, Policies<NoSync, ArrayStorage>> Sig110;
	Signal1<int, Policies<NoSync, SortedArrayStorage>> Sig111;
	Signal1<int, Policies<NoSync, SetStorage>> Sig112;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>>> Sig113;
	Signal1<int, Policies<NoSync, NoResult>> Sig114;
	Signal1<int, Policies<NoSync, All<true>>> Sig115;
	Signal1<int, Policies<NoSync, Any<true>>> Sig116;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg>> Sig117;
	Signal1<int, Policies<NoSync, ArrayStorage>> Sig118;
	Signal1<int, Policies<NoSync, ArrayStorage, NoResult>> Sig119;
	Signal1<int, Policies<NoSync, ArrayStorage, All<true>>> Sig120;
	Signal1<int, Policies<NoSync, ArrayStorage, Any<true>>> Sig121;
	Signal1<int, Policies<NoSync, ArrayStorage, detail::DefaultPoliciesArg>> Sig122;
	Signal1<int, Policies<NoSync, SortedArrayStorage>> Sig123;
	Signal1<int, Policies<NoSync, SortedArrayStorage, NoResult>> Sig124;
	Signal1<int, Policies<NoSync, SortedArrayStorage, All<true>>> Sig125;
	Signal1<int, Policies<NoSync, SortedArrayStorage, Any<true>>> Sig126;
	Signal1<int, Policies<NoSync, SortedArrayStorage, detail::DefaultPoliciesArg>> Sig127;
	Signal1<int, Policies<NoSync, SetStorage>> Sig128;
	Signal1<int, Policies<NoSync, SetStorage, NoResult>> Sig129;
	Signal1<int, Policies<NoSync, SetStorage, All<true>>> Sig130;
	Signal1<int, Policies<NoSync, SetStorage, Any<true>>> Sig131;
	Signal1<int, Policies<NoSync, SetStorage, detail::DefaultPoliciesArg>> Sig132;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>>> Sig133;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>, NoResult>> Sig134;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>, All<true>>> Sig135;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>, Any<true>>> Sig136;
	Signal1<int, Policies<NoSync, FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig137;
	Signal1<int, Policies<NoSync, NoResult>> Sig138;
	Signal1<int, Policies<NoSync, NoResult, ArrayStorage>> Sig139;
	Signal1<int, Policies<NoSync, NoResult, SortedArrayStorage>> Sig140;
	Signal1<int, Policies<NoSync, NoResult, SetStorage>> Sig141;
	Signal1<int, Policies<NoSync, NoResult, FixedArrayStorage<20>>> Sig142;
	Signal1<int, Policies<NoSync, NoResult, detail::DefaultPoliciesArg>> Sig143;
	Signal1<int, Policies<NoSync, All<true>>> Sig144;
	Signal1<int, Policies<NoSync, All<true>, ArrayStorage>> Sig145;
	Signal1<int, Policies<NoSync, All<true>, SortedArrayStorage>> Sig146;
	Signal1<int, Policies<NoSync, All<true>, SetStorage>> Sig147;
	Signal1<int, Policies<NoSync, All<true>, FixedArrayStorage<20>>> Sig148;
	Signal1<int, Policies<NoSync, All<true>, detail::DefaultPoliciesArg>> Sig149;
	Signal1<int, Policies<NoSync, Any<true>>> Sig150;
	Signal1<int, Policies<NoSync, Any<true>, ArrayStorage>> Sig151;
	Signal1<int, Policies<NoSync, Any<true>, SortedArrayStorage>> Sig152;
	Signal1<int, Policies<NoSync, Any<true>, SetStorage>> Sig153;
	Signal1<int, Policies<NoSync, Any<true>, FixedArrayStorage<20>>> Sig154;
	Signal1<int, Policies<NoSync, Any<true>, detail::DefaultPoliciesArg>> Sig155;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg>> Sig156;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, ArrayStorage>> Sig157;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, SortedArrayStorage>> Sig158;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, SetStorage>> Sig159;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig160;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, NoResult>> Sig161;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, All<true>>> Sig162;
	Signal1<int, Policies<NoSync, detail::DefaultPoliciesArg, Any<true>>> Sig163;
	Signal1<int, Policies<InstanceLock>> Sig164;
	Signal1<int, Policies<InstanceLock, ArrayStorage>> Sig165;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage>> Sig166;
	Signal1<int, Policies<InstanceLock, SetStorage>> Sig167;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>>> Sig168;
	Signal1<int, Policies<InstanceLock, NoResult>> Sig169;
	Signal1<int, Policies<InstanceLock, All<true>>> Sig170;
	Signal1<int, Policies<InstanceLock, Any<true>>> Sig171;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg>> Sig172;
	Signal1<int, Policies<InstanceLock, ArrayStorage>> Sig173;
	Signal1<int, Policies<InstanceLock, ArrayStorage, NoResult>> Sig174;
	Signal1<int, Policies<InstanceLock, ArrayStorage, All<true>>> Sig175;
	Signal1<int, Policies<InstanceLock, ArrayStorage, Any<true>>> Sig176;
	Signal1<int, Policies<InstanceLock, ArrayStorage, detail::DefaultPoliciesArg>> Sig177;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage>> Sig178;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage, NoResult>> Sig179;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage, All<true>>> Sig180;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage, Any<true>>> Sig181;
	Signal1<int, Policies<InstanceLock, SortedArrayStorage, detail::DefaultPoliciesArg>> Sig182;
	Signal1<int, Policies<InstanceLock, SetStorage>> Sig183;
	Signal1<int, Policies<InstanceLock, SetStorage, NoResult>> Sig184;
	Signal1<int, Policies<InstanceLock, SetStorage, All<true>>> Sig185;
	Signal1<int, Policies<InstanceLock, SetStorage, Any<true>>> Sig186;
	Signal1<int, Policies<InstanceLock, SetStorage, detail::DefaultPoliciesArg>> Sig187;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>>> Sig188;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>, NoResult>> Sig189;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>, All<true>>> Sig190;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>, Any<true>>> Sig191;
	Signal1<int, Policies<InstanceLock, FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig192;
	Signal1<int, Policies<InstanceLock, NoResult>> Sig193;
	Signal1<int, Policies<InstanceLock, NoResult, ArrayStorage>> Sig194;
	Signal1<int, Policies<InstanceLock, NoResult, SortedArrayStorage>> Sig195;
	Signal1<int, Policies<InstanceLock, NoResult, SetStorage>> Sig196;
	Signal1<int, Policies<InstanceLock, NoResult, FixedArrayStorage<20>>> Sig197;
	Signal1<int, Policies<InstanceLock, NoResult, detail::DefaultPoliciesArg>> Sig198;
	Signal1<int, Policies<InstanceLock, All<true>>> Sig199;
	Signal1<int, Policies<InstanceLock, All<true>, ArrayStorage>> Sig200;
	Signal1<int, Policies<InstanceLock, All<true>, SortedArrayStorage>> Sig201;
	Signal1<int, Policies<InstanceLock, All<true>, SetStorage>> Sig202;
	Signal1<int, Policies<InstanceLock, All<true>, FixedArrayStorage<20>>> Sig203;
	Signal1<int, Policies<InstanceLock, All<true>, detail::DefaultPoliciesArg>> Sig204;
	Signal1<int, Policies<InstanceLock, Any<true>>> Sig205;
	Signal1<int, Policies<InstanceLock, Any<true>, ArrayStorage>> Sig206;
	Signal1<int, Policies<InstanceLock, Any<true>, SortedArrayStorage>> Sig207;
	Signal1<int, Policies<InstanceLock, Any<true>, SetStorage>> Sig208;
	Signal1<int, Policies<InstanceLock, Any<true>, FixedArrayStorage<20>>> Sig209;
	Signal1<int, Policies<InstanceLock, Any<true>, detail::DefaultPoliciesArg>> Sig210;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg>> Sig211;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, ArrayStorage>> Sig212;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, SortedArrayStorage>> Sig213;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, SetStorage>> Sig214;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig215;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, NoResult>> Sig216;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, All<true>>> Sig217;
	Signal1<int, Policies<InstanceLock, detail::DefaultPoliciesArg, Any<true>>> Sig218;
	Signal1<int, Policies<ProcesswideLock>> Sig219;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage>> Sig220;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage>> Sig221;
	Signal1<int, Policies<ProcesswideLock, SetStorage>> Sig222;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>>> Sig223;
	Signal1<int, Policies<ProcesswideLock, NoResult>> Sig224;
	Signal1<int, Policies<ProcesswideLock, All<true>>> Sig225;
	Signal1<int, Policies<ProcesswideLock, Any<true>>> Sig226;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg>> Sig227;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage>> Sig228;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage, NoResult>> Sig229;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage, All<true>>> Sig230;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage, Any<true>>> Sig231;
	Signal1<int, Policies<ProcesswideLock, ArrayStorage, detail::DefaultPoliciesArg>> Sig232;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage>> Sig233;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage, NoResult>> Sig234;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage, All<true>>> Sig235;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage, Any<true>>> Sig236;
	Signal1<int, Policies<ProcesswideLock, SortedArrayStorage, detail::DefaultPoliciesArg>> Sig237;
	Signal1<int, Policies<ProcesswideLock, SetStorage>> Sig238;
	Signal1<int, Policies<ProcesswideLock, SetStorage, NoResult>> Sig239;
	Signal1<int, Policies<ProcesswideLock, SetStorage, All<true>>> Sig240;
	Signal1<int, Policies<ProcesswideLock, SetStorage, Any<true>>> Sig241;
	Signal1<int, Policies<ProcesswideLock, SetStorage, detail::DefaultPoliciesArg>> Sig242;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>>> Sig243;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>, NoResult>> Sig244;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>, All<true>>> Sig245;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>, Any<true>>> Sig246;
	Signal1<int, Policies<ProcesswideLock, FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig247;
	Signal1<int, Policies<ProcesswideLock, NoResult>> Sig248;
	Signal1<int, Policies<ProcesswideLock, NoResult, ArrayStorage>> Sig249;
	Signal1<int, Policies<ProcesswideLock, NoResult, SortedArrayStorage>> Sig250;
	Signal1<int, Policies<ProcesswideLock, NoResult, SetStorage>> Sig251;
	Signal1<int, Policies<ProcesswideLock, NoResult, FixedArrayStorage<20>>> Sig252;
	Signal1<int, Policies<ProcesswideLock, NoResult, detail::DefaultPoliciesArg>> Sig253;
	Signal1<int, Policies<ProcesswideLock, All<true>>> Sig254;
	Signal1<int, Policies<ProcesswideLock, All<true>, ArrayStorage>> Sig255;
	Signal1<int, Policies<ProcesswideLock, All<true>, SortedArrayStorage>> Sig256;
	Signal1<int, Policies<ProcesswideLock, All<true>, SetStorage>> Sig257;
	Signal1<int, Policies<ProcesswideLock, All<true>, FixedArrayStorage<20>>> Sig258;
	Signal1<int, Policies<ProcesswideLock, All<true>, detail::DefaultPoliciesArg>> Sig259;
	Signal1<int, Policies<ProcesswideLock, Any<true>>> Sig260;
	Signal1<int, Policies<ProcesswideLock, Any<true>, ArrayStorage>> Sig261;
	Signal1<int, Policies<ProcesswideLock, Any<true>, SortedArrayStorage>> Sig262;
	Signal1<int, Policies<ProcesswideLock, Any<true>, SetStorage>> Sig263;
	Signal1<int, Policies<ProcesswideLock, Any<true>, FixedArrayStorage<20>>> Sig264;
	Signal1<int, Policies<ProcesswideLock, Any<true>, detail::DefaultPoliciesArg>> Sig265;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg>> Sig266;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, ArrayStorage>> Sig267;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, SortedArrayStorage>> Sig268;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, SetStorage>> Sig269;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig270;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, NoResult>> Sig271;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, All<true>>> Sig272;
	Signal1<int, Policies<ProcesswideLock, detail::DefaultPoliciesArg, Any<true>>> Sig273;
	Signal1<int, Policies<ArrayStorage>> Sig274;
	Signal1<int, Policies<ArrayStorage, NoSync>> Sig275;
	Signal1<int, Policies<ArrayStorage, InstanceLock>> Sig276;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock>> Sig277;
	Signal1<int, Policies<ArrayStorage, NoResult>> Sig278;
	Signal1<int, Policies<ArrayStorage, All<true>>> Sig279;
	Signal1<int, Policies<ArrayStorage, Any<true>>> Sig280;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg>> Sig281;
	Signal1<int, Policies<ArrayStorage, NoSync>> Sig282;
	Signal1<int, Policies<ArrayStorage, NoSync, NoResult>> Sig283;
	Signal1<int, Policies<ArrayStorage, NoSync, All<true>>> Sig284;
	Signal1<int, Policies<ArrayStorage, NoSync, Any<true>>> Sig285;
	Signal1<int, Policies<ArrayStorage, NoSync, detail::DefaultPoliciesArg>> Sig286;
	Signal1<int, Policies<ArrayStorage, InstanceLock>> Sig287;
	Signal1<int, Policies<ArrayStorage, InstanceLock, NoResult>> Sig288;
	Signal1<int, Policies<ArrayStorage, InstanceLock, All<true>>> Sig289;
	Signal1<int, Policies<ArrayStorage, InstanceLock, Any<true>>> Sig290;
	Signal1<int, Policies<ArrayStorage, InstanceLock, detail::DefaultPoliciesArg>> Sig291;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock>> Sig292;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock, NoResult>> Sig293;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock, All<true>>> Sig294;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock, Any<true>>> Sig295;
	Signal1<int, Policies<ArrayStorage, ProcesswideLock, detail::DefaultPoliciesArg>> Sig296;
	Signal1<int, Policies<ArrayStorage, NoResult>> Sig297;
	Signal1<int, Policies<ArrayStorage, NoResult, NoSync>> Sig298;
	Signal1<int, Policies<ArrayStorage, NoResult, InstanceLock>> Sig299;
	Signal1<int, Policies<ArrayStorage, NoResult, ProcesswideLock>> Sig300;
	Signal1<int, Policies<ArrayStorage, NoResult, detail::DefaultPoliciesArg>> Sig301;
	Signal1<int, Policies<ArrayStorage, All<true>>> Sig302;
	Signal1<int, Policies<ArrayStorage, All<true>, NoSync>> Sig303;
	Signal1<int, Policies<ArrayStorage, All<true>, InstanceLock>> Sig304;
	Signal1<int, Policies<ArrayStorage, All<true>, ProcesswideLock>> Sig305;
	Signal1<int, Policies<ArrayStorage, All<true>, detail::DefaultPoliciesArg>> Sig306;
	Signal1<int, Policies<ArrayStorage, Any<true>>> Sig307;
	Signal1<int, Policies<ArrayStorage, Any<true>, NoSync>> Sig308;
	Signal1<int, Policies<ArrayStorage, Any<true>, InstanceLock>> Sig309;
	Signal1<int, Policies<ArrayStorage, Any<true>, ProcesswideLock>> Sig310;
	Signal1<int, Policies<ArrayStorage, Any<true>, detail::DefaultPoliciesArg>> Sig311;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg>> Sig312;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg, NoSync>> Sig313;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg, InstanceLock>> Sig314;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg, ProcesswideLock>> Sig315;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg, NoResult>> Sig316;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg, All<true>>> Sig317;
	Signal1<int, Policies<ArrayStorage, detail::DefaultPoliciesArg, Any<true>>> Sig318;
	Signal1<int, Policies<SortedArrayStorage>> Sig319;
	Signal1<int, Policies<SortedArrayStorage, NoSync>> Sig320;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock>> Sig321;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock>> Sig322;
	Signal1<int, Policies<SortedArrayStorage, NoResult>> Sig323;
	Signal1<int, Policies<SortedArrayStorage, All<true>>> Sig324;
	Signal1<int, Policies<SortedArrayStorage, Any<true>>> Sig325;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg>> Sig326;
	Signal1<int, Policies<SortedArrayStorage, NoSync>> Sig327;
	Signal1<int, Policies<SortedArrayStorage, NoSync, NoResult>> Sig328;
	Signal1<int, Policies<SortedArrayStorage, NoSync, All<true>>> Sig329;
	Signal1<int, Policies<SortedArrayStorage, NoSync, Any<true>>> Sig330;
	Signal1<int, Policies<SortedArrayStorage, NoSync, detail::DefaultPoliciesArg>> Sig331;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock>> Sig332;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock, NoResult>> Sig333;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock, All<true>>> Sig334;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock, Any<true>>> Sig335;
	Signal1<int, Policies<SortedArrayStorage, InstanceLock, detail::DefaultPoliciesArg>> Sig336;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock>> Sig337;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock, NoResult>> Sig338;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock, All<true>>> Sig339;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock, Any<true>>> Sig340;
	Signal1<int, Policies<SortedArrayStorage, ProcesswideLock, detail::DefaultPoliciesArg>> Sig341;
	Signal1<int, Policies<SortedArrayStorage, NoResult>> Sig342;
	Signal1<int, Policies<SortedArrayStorage, NoResult, NoSync>> Sig343;
	Signal1<int, Policies<SortedArrayStorage, NoResult, InstanceLock>> Sig344;
	Signal1<int, Policies<SortedArrayStorage, NoResult, ProcesswideLock>> Sig345;
	Signal1<int, Policies<SortedArrayStorage, NoResult, detail::DefaultPoliciesArg>> Sig346;
	Signal1<int, Policies<SortedArrayStorage, All<true>>> Sig347;
	Signal1<int, Policies<SortedArrayStorage, All<true>, NoSync>> Sig348;
	Signal1<int, Policies<SortedArrayStorage, All<true>, InstanceLock>> Sig349;
	Signal1<int, Policies<SortedArrayStorage, All<true>, ProcesswideLock>> Sig350;
	Signal1<int, Policies<SortedArrayStorage, All<true>, detail::DefaultPoliciesArg>> Sig351;
	Signal1<int, Policies<SortedArrayStorage, Any<true>>> Sig352;
	Signal1<int, Policies<SortedArrayStorage, Any<true>, NoSync>> Sig353;
	Signal1<int, Policies<SortedArrayStorage, Any<true>, InstanceLock>> Sig354;
	Signal1<int, Policies<SortedArrayStorage, Any<true>, ProcesswideLock>> Sig355;
	Signal1<int, Policies<SortedArrayStorage, Any<true>, detail::DefaultPoliciesArg>> Sig356;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg>> Sig357;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg, NoSync>> Sig358;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg, InstanceLock>> Sig359;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg, ProcesswideLock>> Sig360;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg, NoResult>> Sig361;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg, All<true>>> Sig362;
	Signal1<int, Policies<SortedArrayStorage, detail::DefaultPoliciesArg, Any<true>>> Sig363;
	Signal1<int, Policies<SetStorage>> Sig364;
	Signal1<int, Policies<SetStorage, NoSync>> Sig365;
	Signal1<int, Policies<SetStorage, InstanceLock>> Sig366;
	Signal1<int, Policies<SetStorage, ProcesswideLock>> Sig367;
	Signal1<int, Policies<SetStorage, NoResult>> Sig368;
	Signal1<int, Policies<SetStorage, All<true>>> Sig369;
	Signal1<int, Policies<SetStorage, Any<true>>> Sig370;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg>> Sig371;
	Signal1<int, Policies<SetStorage, NoSync>> Sig372;
	Signal1<int, Policies<SetStorage, NoSync, NoResult>> Sig373;
	Signal1<int, Policies<SetStorage, NoSync, All<true>>> Sig374;
	Signal1<int, Policies<SetStorage, NoSync, Any<true>>> Sig375;
	Signal1<int, Policies<SetStorage, NoSync, detail::DefaultPoliciesArg>> Sig376;
	Signal1<int, Policies<SetStorage, InstanceLock>> Sig377;
	Signal1<int, Policies<SetStorage, InstanceLock, NoResult>> Sig378;
	Signal1<int, Policies<SetStorage, InstanceLock, All<true>>> Sig379;
	Signal1<int, Policies<SetStorage, InstanceLock, Any<true>>> Sig380;
	Signal1<int, Policies<SetStorage, InstanceLock, detail::DefaultPoliciesArg>> Sig381;
	Signal1<int, Policies<SetStorage, ProcesswideLock>> Sig382;
	Signal1<int, Policies<SetStorage, ProcesswideLock, NoResult>> Sig383;
	Signal1<int, Policies<SetStorage, ProcesswideLock, All<true>>> Sig384;
	Signal1<int, Policies<SetStorage, ProcesswideLock, Any<true>>> Sig385;
	Signal1<int, Policies<SetStorage, ProcesswideLock, detail::DefaultPoliciesArg>> Sig386;
	Signal1<int, Policies<SetStorage, NoResult>> Sig387;
	Signal1<int, Policies<SetStorage, NoResult, NoSync>> Sig388;
	Signal1<int, Policies<SetStorage, NoResult, InstanceLock>> Sig389;
	Signal1<int, Policies<SetStorage, NoResult, ProcesswideLock>> Sig390;
	Signal1<int, Policies<SetStorage, NoResult, detail::DefaultPoliciesArg>> Sig391;
	Signal1<int, Policies<SetStorage, All<true>>> Sig392;
	Signal1<int, Policies<SetStorage, All<true>, NoSync>> Sig393;
	Signal1<int, Policies<SetStorage, All<true>, InstanceLock>> Sig394;
	Signal1<int, Policies<SetStorage, All<true>, ProcesswideLock>> Sig395;
	Signal1<int, Policies<SetStorage, All<true>, detail::DefaultPoliciesArg>> Sig396;
	Signal1<int, Policies<SetStorage, Any<true>>> Sig397;
	Signal1<int, Policies<SetStorage, Any<true>, NoSync>> Sig398;
	Signal1<int, Policies<SetStorage, Any<true>, InstanceLock>> Sig399;
	Signal1<int, Policies<SetStorage, Any<true>, ProcesswideLock>> Sig400;
	Signal1<int, Policies<SetStorage, Any<true>, detail::DefaultPoliciesArg>> Sig401;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg>> Sig402;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg, NoSync>> Sig403;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg, InstanceLock>> Sig404;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg, ProcesswideLock>> Sig405;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg, NoResult>> Sig406;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg, All<true>>> Sig407;
	Signal1<int, Policies<SetStorage, detail::DefaultPoliciesArg, Any<true>>> Sig408;
	Signal1<int, Policies<FixedArrayStorage<20>>> Sig409;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync>> Sig410;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock>> Sig411;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock>> Sig412;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult>> Sig413;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>>> Sig414;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>>> Sig415;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig416;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync>> Sig417;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync, NoResult>> Sig418;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync, All<true>>> Sig419;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync, Any<true>>> Sig420;
	Signal1<int, Policies<FixedArrayStorage<20>, NoSync, detail::DefaultPoliciesArg>> Sig421;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock>> Sig422;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock, NoResult>> Sig423;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock, All<true>>> Sig424;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock, Any<true>>> Sig425;
	Signal1<int, Policies<FixedArrayStorage<20>, InstanceLock, detail::DefaultPoliciesArg>> Sig426;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock>> Sig427;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock, NoResult>> Sig428;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock, All<true>>> Sig429;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock, Any<true>>> Sig430;
	Signal1<int, Policies<FixedArrayStorage<20>, ProcesswideLock, detail::DefaultPoliciesArg>> Sig431;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult>> Sig432;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult, NoSync>> Sig433;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult, InstanceLock>> Sig434;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult, ProcesswideLock>> Sig435;
	Signal1<int, Policies<FixedArrayStorage<20>, NoResult, detail::DefaultPoliciesArg>> Sig436;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>>> Sig437;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>, NoSync>> Sig438;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>, InstanceLock>> Sig439;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>, ProcesswideLock>> Sig440;
	Signal1<int, Policies<FixedArrayStorage<20>, All<true>, detail::DefaultPoliciesArg>> Sig441;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>>> Sig442;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>, NoSync>> Sig443;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>, InstanceLock>> Sig444;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>, ProcesswideLock>> Sig445;
	Signal1<int, Policies<FixedArrayStorage<20>, Any<true>, detail::DefaultPoliciesArg>> Sig446;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig447;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg, NoSync>> Sig448;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg, InstanceLock>> Sig449;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg, ProcesswideLock>> Sig450;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg, NoResult>> Sig451;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg, All<true>>> Sig452;
	Signal1<int, Policies<FixedArrayStorage<20>, detail::DefaultPoliciesArg, Any<true>>> Sig453;
	Signal1<int, Policies<NoResult>> Sig454;
	Signal1<int, Policies<NoResult, NoSync>> Sig455;
	Signal1<int, Policies<NoResult, InstanceLock>> Sig456;
	Signal1<int, Policies<NoResult, ProcesswideLock>> Sig457;
	Signal1<int, Policies<NoResult, ArrayStorage>> Sig458;
	Signal1<int, Policies<NoResult, SortedArrayStorage>> Sig459;
	Signal1<int, Policies<NoResult, SetStorage>> Sig460;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>>> Sig461;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg>> Sig462;
	Signal1<int, Policies<NoResult, NoSync>> Sig463;
	Signal1<int, Policies<NoResult, NoSync, ArrayStorage>> Sig464;
	Signal1<int, Policies<NoResult, NoSync, SortedArrayStorage>> Sig465;
	Signal1<int, Policies<NoResult, NoSync, SetStorage>> Sig466;
	Signal1<int, Policies<NoResult, NoSync, FixedArrayStorage<20>>> Sig467;
	Signal1<int, Policies<NoResult, NoSync, detail::DefaultPoliciesArg>> Sig468;
	Signal1<int, Policies<NoResult, InstanceLock>> Sig469;
	Signal1<int, Policies<NoResult, InstanceLock, ArrayStorage>> Sig470;
	Signal1<int, Policies<NoResult, InstanceLock, SortedArrayStorage>> Sig471;
	Signal1<int, Policies<NoResult, InstanceLock, SetStorage>> Sig472;
	Signal1<int, Policies<NoResult, InstanceLock, FixedArrayStorage<20>>> Sig473;
	Signal1<int, Policies<NoResult, InstanceLock, detail::DefaultPoliciesArg>> Sig474;
	Signal1<int, Policies<NoResult, ProcesswideLock>> Sig475;
	Signal1<int, Policies<NoResult, ProcesswideLock, ArrayStorage>> Sig476;
	Signal1<int, Policies<NoResult, ProcesswideLock, SortedArrayStorage>> Sig477;
	Signal1<int, Policies<NoResult, ProcesswideLock, SetStorage>> Sig478;
	Signal1<int, Policies<NoResult, ProcesswideLock, FixedArrayStorage<20>>> Sig479;
	Signal1<int, Policies<NoResult, ProcesswideLock, detail::DefaultPoliciesArg>> Sig480;
	Signal1<int, Policies<NoResult, ArrayStorage>> Sig481;
	Signal1<int, Policies<NoResult, ArrayStorage, NoSync>> Sig482;
	Signal1<int, Policies<NoResult, ArrayStorage, InstanceLock>> Sig483;
	Signal1<int, Policies<NoResult, ArrayStorage, ProcesswideLock>> Sig484;
	Signal1<int, Policies<NoResult, ArrayStorage, detail::DefaultPoliciesArg>> Sig485;
	Signal1<int, Policies<NoResult, SortedArrayStorage>> Sig486;
	Signal1<int, Policies<NoResult, SortedArrayStorage, NoSync>> Sig487;
	Signal1<int, Policies<NoResult, SortedArrayStorage, InstanceLock>> Sig488;
	Signal1<int, Policies<NoResult, SortedArrayStorage, ProcesswideLock>> Sig489;
	Signal1<int, Policies<NoResult, SortedArrayStorage, detail::DefaultPoliciesArg>> Sig490;
	Signal1<int, Policies<NoResult, SetStorage>> Sig491;
	Signal1<int, Policies<NoResult, SetStorage, NoSync>> Sig492;
	Signal1<int, Policies<NoResult, SetStorage, InstanceLock>> Sig493;
	Signal1<int, Policies<NoResult, SetStorage, ProcesswideLock>> Sig494;
	Signal1<int, Policies<NoResult, SetStorage, detail::DefaultPoliciesArg>> Sig495;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>>> Sig496;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>, NoSync>> Sig497;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>, InstanceLock>> Sig498;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>, ProcesswideLock>> Sig499;
	Signal1<int, Policies<NoResult, FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig500;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg>> Sig501;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, NoSync>> Sig502;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, InstanceLock>> Sig503;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, ProcesswideLock>> Sig504;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, ArrayStorage>> Sig505;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, SortedArrayStorage>> Sig506;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, SetStorage>> Sig507;
	Signal1<int, Policies<NoResult, detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig508;
	Signal1<int, Policies<All<true>>> Sig509;
	Signal1<int, Policies<All<true>, NoSync>> Sig510;
	Signal1<int, Policies<All<true>, InstanceLock>> Sig511;
	Signal1<int, Policies<All<true>, ProcesswideLock>> Sig512;
	Signal1<int, Policies<All<true>, ArrayStorage>> Sig513;
	Signal1<int, Policies<All<true>, SortedArrayStorage>> Sig514;
	Signal1<int, Policies<All<true>, SetStorage>> Sig515;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>>> Sig516;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg>> Sig517;
	Signal1<int, Policies<All<true>, NoSync>> Sig518;
	Signal1<int, Policies<All<true>, NoSync, ArrayStorage>> Sig519;
	Signal1<int, Policies<All<true>, NoSync, SortedArrayStorage>> Sig520;
	Signal1<int, Policies<All<true>, NoSync, SetStorage>> Sig521;
	Signal1<int, Policies<All<true>, NoSync, FixedArrayStorage<20>>> Sig522;
	Signal1<int, Policies<All<true>, NoSync, detail::DefaultPoliciesArg>> Sig523;
	Signal1<int, Policies<All<true>, InstanceLock>> Sig524;
	Signal1<int, Policies<All<true>, InstanceLock, ArrayStorage>> Sig525;
	Signal1<int, Policies<All<true>, InstanceLock, SortedArrayStorage>> Sig526;
	Signal1<int, Policies<All<true>, InstanceLock, SetStorage>> Sig527;
	Signal1<int, Policies<All<true>, InstanceLock, FixedArrayStorage<20>>> Sig528;
	Signal1<int, Policies<All<true>, InstanceLock, detail::DefaultPoliciesArg>> Sig529;
	Signal1<int, Policies<All<true>, ProcesswideLock>> Sig530;
	Signal1<int, Policies<All<true>, ProcesswideLock, ArrayStorage>> Sig531;
	Signal1<int, Policies<All<true>, ProcesswideLock, SortedArrayStorage>> Sig532;
	Signal1<int, Policies<All<true>, ProcesswideLock, SetStorage>> Sig533;
	Signal1<int, Policies<All<true>, ProcesswideLock, FixedArrayStorage<20>>> Sig534;
	Signal1<int, Policies<All<true>, ProcesswideLock, detail::DefaultPoliciesArg>> Sig535;
	Signal1<int, Policies<All<true>, ArrayStorage>> Sig536;
	Signal1<int, Policies<All<true>, ArrayStorage, NoSync>> Sig537;
	Signal1<int, Policies<All<true>, ArrayStorage, InstanceLock>> Sig538;
	Signal1<int, Policies<All<true>, ArrayStorage, ProcesswideLock>> Sig539;
	Signal1<int, Policies<All<true>, ArrayStorage, detail::DefaultPoliciesArg>> Sig540;
	Signal1<int, Policies<All<true>, SortedArrayStorage>> Sig541;
	Signal1<int, Policies<All<true>, SortedArrayStorage, NoSync>> Sig542;
	Signal1<int, Policies<All<true>, SortedArrayStorage, InstanceLock>> Sig543;
	Signal1<int, Policies<All<true>, SortedArrayStorage, ProcesswideLock>> Sig544;
	Signal1<int, Policies<All<true>, SortedArrayStorage, detail::DefaultPoliciesArg>> Sig545;
	Signal1<int, Policies<All<true>, SetStorage>> Sig546;
	Signal1<int, Policies<All<true>, SetStorage, NoSync>> Sig547;
	Signal1<int, Policies<All<true>, SetStorage, InstanceLock>> Sig548;
	Signal1<int, Policies<All<true>, SetStorage, ProcesswideLock>> Sig549;
	Signal1<int, Policies<All<true>, SetStorage, detail::DefaultPoliciesArg>> Sig550;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>>> Sig551;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>, NoSync>> Sig552;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>, InstanceLock>> Sig553;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>, ProcesswideLock>> Sig554;
	Signal1<int, Policies<All<true>, FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig555;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg>> Sig556;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, NoSync>> Sig557;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, InstanceLock>> Sig558;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, ProcesswideLock>> Sig559;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, ArrayStorage>> Sig560;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, SortedArrayStorage>> Sig561;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, SetStorage>> Sig562;
	Signal1<int, Policies<All<true>, detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig563;
	Signal1<int, Policies<Any<true>>> Sig564;
	Signal1<int, Policies<Any<true>, NoSync>> Sig565;
	Signal1<int, Policies<Any<true>, InstanceLock>> Sig566;
	Signal1<int, Policies<Any<true>, ProcesswideLock>> Sig567;
	Signal1<int, Policies<Any<true>, ArrayStorage>> Sig568;
	Signal1<int, Policies<Any<true>, SortedArrayStorage>> Sig569;
	Signal1<int, Policies<Any<true>, SetStorage>> Sig570;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>>> Sig571;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg>> Sig572;
	Signal1<int, Policies<Any<true>, NoSync>> Sig573;
	Signal1<int, Policies<Any<true>, NoSync, ArrayStorage>> Sig574;
	Signal1<int, Policies<Any<true>, NoSync, SortedArrayStorage>> Sig575;
	Signal1<int, Policies<Any<true>, NoSync, SetStorage>> Sig576;
	Signal1<int, Policies<Any<true>, NoSync, FixedArrayStorage<20>>> Sig577;
	Signal1<int, Policies<Any<true>, NoSync, detail::DefaultPoliciesArg>> Sig578;
	Signal1<int, Policies<Any<true>, InstanceLock>> Sig579;
	Signal1<int, Policies<Any<true>, InstanceLock, ArrayStorage>> Sig580;
	Signal1<int, Policies<Any<true>, InstanceLock, SortedArrayStorage>> Sig581;
	Signal1<int, Policies<Any<true>, InstanceLock, SetStorage>> Sig582;
	Signal1<int, Policies<Any<true>, InstanceLock, FixedArrayStorage<20>>> Sig583;
	Signal1<int, Policies<Any<true>, InstanceLock, detail::DefaultPoliciesArg>> Sig584;
	Signal1<int, Policies<Any<true>, ProcesswideLock>> Sig585;
	Signal1<int, Policies<Any<true>, ProcesswideLock, ArrayStorage>> Sig586;
	Signal1<int, Policies<Any<true>, ProcesswideLock, SortedArrayStorage>> Sig587;
	Signal1<int, Policies<Any<true>, ProcesswideLock, SetStorage>> Sig588;
	Signal1<int, Policies<Any<true>, ProcesswideLock, FixedArrayStorage<20>>> Sig589;
	Signal1<int, Policies<Any<true>, ProcesswideLock, detail::DefaultPoliciesArg>> Sig590;
	Signal1<int, Policies<Any<true>, ArrayStorage>> Sig591;
	Signal1<int, Policies<Any<true>, ArrayStorage, NoSync>> Sig592;
	Signal1<int, Policies<Any<true>, ArrayStorage, InstanceLock>> Sig593;
	Signal1<int, Policies<Any<true>, ArrayStorage, ProcesswideLock>> Sig594;
	Signal1<int, Policies<Any<true>, ArrayStorage, detail::DefaultPoliciesArg>> Sig595;
	Signal1<int, Policies<Any<true>, SortedArrayStorage>> Sig596;
	Signal1<int, Policies<Any<true>, SortedArrayStorage, NoSync>> Sig597;
	Signal1<int, Policies<Any<true>, SortedArrayStorage, InstanceLock>> Sig598;
	Signal1<int, Policies<Any<true>, SortedArrayStorage, ProcesswideLock>> Sig599;
	Signal1<int, Policies<Any<true>, SortedArrayStorage, detail::DefaultPoliciesArg>> Sig600;
	Signal1<int, Policies<Any<true>, SetStorage>> Sig601;
	Signal1<int, Policies<Any<true>, SetStorage, NoSync>> Sig602;
	Signal1<int, Policies<Any<true>, SetStorage, InstanceLock>> Sig603;
	Signal1<int, Policies<Any<true>, SetStorage, ProcesswideLock>> Sig604;
	Signal1<int, Policies<Any<true>, SetStorage, detail::DefaultPoliciesArg>> Sig605;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>>> Sig606;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>, NoSync>> Sig607;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>, InstanceLock>> Sig608;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>, ProcesswideLock>> Sig609;
	Signal1<int, Policies<Any<true>, FixedArrayStorage<20>, detail::DefaultPoliciesArg>> Sig610;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg>> Sig611;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, NoSync>> Sig612;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, InstanceLock>> Sig613;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, ProcesswideLock>> Sig614;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, ArrayStorage>> Sig615;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, SortedArrayStorage>> Sig616;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, SetStorage>> Sig617;
	Signal1<int, Policies<Any<true>, detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig618;
	Signal1<int, Policies<detail::DefaultPoliciesArg>> Sig619;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync>> Sig620;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock>> Sig621;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock>> Sig622;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage>> Sig623;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage>> Sig624;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage>> Sig625;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig626;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult>> Sig627;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>>> Sig628;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>>> Sig629;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync>> Sig630;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, ArrayStorage>> Sig631;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, SortedArrayStorage>> Sig632;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, SetStorage>> Sig633;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, FixedArrayStorage<20>>> Sig634;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, NoResult>> Sig635;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, All<true>>> Sig636;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoSync, Any<true>>> Sig637;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock>> Sig638;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, ArrayStorage>> Sig639;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, SortedArrayStorage>> Sig640;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, SetStorage>> Sig641;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, FixedArrayStorage<20>>> Sig642;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, NoResult>> Sig643;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, All<true>>> Sig644;
	Signal1<int, Policies<detail::DefaultPoliciesArg, InstanceLock, Any<true>>> Sig645;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock>> Sig646;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, ArrayStorage>> Sig647;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, SortedArrayStorage>> Sig648;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, SetStorage>> Sig649;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, FixedArrayStorage<20>>> Sig650;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, NoResult>> Sig651;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, All<true>>> Sig652;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ProcesswideLock, Any<true>>> Sig653;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage>> Sig654;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage, NoSync>> Sig655;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage, InstanceLock>> Sig656;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage, ProcesswideLock>> Sig657;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage, NoResult>> Sig658;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage, All<true>>> Sig659;
	Signal1<int, Policies<detail::DefaultPoliciesArg, ArrayStorage, Any<true>>> Sig660;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage>> Sig661;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage, NoSync>> Sig662;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage, InstanceLock>> Sig663;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage, ProcesswideLock>> Sig664;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage, NoResult>> Sig665;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage, All<true>>> Sig666;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SortedArrayStorage, Any<true>>> Sig667;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage>> Sig668;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage, NoSync>> Sig669;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage, InstanceLock>> Sig670;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage, ProcesswideLock>> Sig671;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage, NoResult>> Sig672;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage, All<true>>> Sig673;
	Signal1<int, Policies<detail::DefaultPoliciesArg, SetStorage, Any<true>>> Sig674;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>>> Sig675;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>, NoSync>> Sig676;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>, InstanceLock>> Sig677;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>, ProcesswideLock>> Sig678;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>, NoResult>> Sig679;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>, All<true>>> Sig680;
	Signal1<int, Policies<detail::DefaultPoliciesArg, FixedArrayStorage<20>, Any<true>>> Sig681;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult>> Sig682;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, NoSync>> Sig683;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, InstanceLock>> Sig684;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, ProcesswideLock>> Sig685;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, ArrayStorage>> Sig686;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, SortedArrayStorage>> Sig687;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, SetStorage>> Sig688;
	Signal1<int, Policies<detail::DefaultPoliciesArg, NoResult, FixedArrayStorage<20>>> Sig689;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>>> Sig690;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, NoSync>> Sig691;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, InstanceLock>> Sig692;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, ProcesswideLock>> Sig693;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, ArrayStorage>> Sig694;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, SortedArrayStorage>> Sig695;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, SetStorage>> Sig696;
	Signal1<int, Policies<detail::DefaultPoliciesArg, All<true>, FixedArrayStorage<20>>> Sig697;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>>> Sig698;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, NoSync>> Sig699;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, InstanceLock>> Sig700;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, ProcesswideLock>> Sig701;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, ArrayStorage>> Sig702;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, SortedArrayStorage>> Sig703;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, SetStorage>> Sig704;
	Signal1<int, Policies<detail::DefaultPoliciesArg, Any<true>, FixedArrayStorage<20>>> Sig705;
}
